config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, controller: 'users', only: [:create] do
    resource :password,
             controller: 'passwords',
             only: [:create, :edit, :update]
  end

  resource :account, only: [:show, :update]

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'

  get '/challenge' => 'challenge#get'

  delete '/sign_out' => 'sessions#destroy', as: 'sign_out'

  root 'application#index'
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :user
  
  def self.resolve(user, session, castle)
    device = Device.find_by_castle_id(session[:castle_id])
    return device if device

    authentication = castle.authentications.create(user_id: user.id)
    device = Device.find_by castle_id: authentication.device_id
    session[:castle_id] = device.castle_id
    return device if device

    device ||= Device.create(user_id: user.id,
                             castle_id: authentication.device_id,
                             latest_authentication_id: authentication.id)

    if authentication.risk > 0.9
      user.lock!
    elsif authentication.risk > 0.6
      device.challenge!
    elsif authentication.risk > 0.3
      # Notify the user about unusual activity
      user.send_notification_email(auth)
    end
    session[:castle_id] = device.castle_id
    device
  end

  def challenge!
    return if challenge_token.present?
    
    self[:challenge_token] = SecureRandom.urlsafe_base64(nil, false)
    save
    user.notify_user_with_challenge(challenge_token, castle_id)
  end

  def challenge?
    challenge_token.present?
  end

  def blocked?
    user.lock?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  def lock!
    unless lock
      update_attribute(:lock, true)
      forgot_password!
      ClearanceMailer.change_password(self).deliver_later
    end
  end

  def unlock!
    update_attribute(:lock, false)
  end

  def challenge(castle_authentication)
    # TODO: Replace with real token
    challenge_token = castle_authentication.id
    UserMailer.challenge(self, challenge_token).deliver_later
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :require_login

  def update
    if current_user.update_attributes params.require(:user).permit(:description)
      redirect_to account_path, notice: 'Saved!'
    else
      redirect_to account_path, notice: 'Something went wrong.'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Clearance::Authentication

  protect_from_forgery with: :exception

  def index
    redirect_to account_path if signed_in?
  end
end

app/controllers/castle_hook_controller.rb
class CastleHookController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :verify_webhook

  def verify_webhook
    data = request.body.read
    hmac_header = request.headers['X-Castle-Signature']
    digest = OpenSSL::Digest::Digest.new('sha256')

    calculated_hmac =
    Base64.encode64(OpenSSL::HMAC.digest(
      digest,
      ENV['CASTLE_API_SECRET'],
      data)
    ).strip

    if calculated_hmac != hmac_header
      respond_to do |format|
        format.json { head :unauthorized }
      end
    end
  end

  def post
    # Retrieve the request's body and parse it as JSON
    auth = Castle::Authentication.new(JSON.parse(request.body.read))

    # Fetch the user from your database
    user = User.find(auth.user_id)
    device = Device.resolve(user, session, castle)
    
    unless device.latest_authentication_id == auth.id
      device.latest_authentication_id = auth.id
      device.save
    end

    if auth.risk > 0.9
      user.lock!
    elsif auth.risk > 0.6
      device.challenge!
    elsif auth.risk > 0.3
      # Notify the user about unusual activity
      user.send_notification_email(auth)
    end

    render nothing: true, status: :ok
  end
end

app/controllers/challenge_controller.rb
SKIP_CASTLE_GUARD = false

class ChallengeController < ApplicationController
  def get
    challenge_token = params[:token]

    # TODO: Replace with real challenge token
    authentication = castle.authentications.find(challenge_token)
    if authentication
      user = User.find(authentication.user_id)
      sign_in(user)
      castle.track(
        name: '$login.succeeded',
        user_id: user.id)

      redirect_to account_path
    end
  end
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  
  def show
    jwt = params[:token]
    decoded = JWT.decode(jwt, ENV['CASTLE_API_SECRET'])
    feedback = decoded[0]
    @user = User.find(feedback['user_id'])
    @user.lock!
    @status = feedback['label']
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Clearance::PasswordsController
  def update
    @user = find_user_for_update

    if @user.update_password password_reset_params
      @user.unlock!
      sign_in_without_castle_guard @user
      redirect_to url_after_update
    else
      flash_failure_after_update
      render template: 'passwords/edit'
    end
  end
end

app/controllers/sessions_controller.rb
LOCK_NOTICE = 'Your account is currently locked.
  Please follow the instructions in the email we\'ve sent.'.freeze

CHALLENGE_NOTICE = 'You need to verify your identity.
  Please follow the instructions in the email we\'ve sent.'.freeze

class SessionsController < Clearance::SessionsController
  before_filter :require_login, only: [:destroy]
  def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
        castle_authentication = castle.authentications.create(user_id: @user.id)
        
        if castle_authentication.risk > 0.9
          current_user.lock!
          castle.track(
            name: '$login.failed',
            user_id: @user.id,
            details: { '$login' => @user.email })
          sign_out
          
          flash.now.notice = LOCK_NOTICE
          render template: 'sessions/new', status: :unauthorized
        elsif castle_authentication.risk > 0.6
          current_user.challenge(castle_authentication)
          sign_out

          flash.now.notice = CHALLENGE_NOTICE
          render template: 'sessions/new', status: :unauthorized
        else
          castle.track(
            name: '$login.succeeded',
            user_id: @user.id)
          redirect_back_or url_after_create
        end
      else
        email = params['session']['email']
        user_id = User.find_by_email(email).id rescue nil
        castle.track(
          name: '$login.failed',
          user_id: user_id,
          details: { '$login' => email })
        
        flash.now.notice = status.failure_message
        render template: 'sessions/new', status: :unauthorized
      end
    end
  end

  def destroy
    castle.track(
      user_id: current_user.id,
      name: '$logout.succeeded')
    super
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def create
    super
    if @user.errors.empty?
      castle.track(
        name: '$login.succeeded',
        user_id: @user.id)
    end
  end
end

app/views/accounts/show.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <h2>You're logged in as <%= current_user.email %></h2>
  </div>
  <div class="col-sm-offset-2 col-sm-4">
    <%= form_for current_user, url: account_path do |f| %>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description,
          class: "form-control",
          placeholder: "Please tell us about yourself." %>
      </div>
      <button type="submit" class="btn btn-danger">Save</button>
    <% end %>
  </div>
</div>

app/views/application/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div style="padding: 40px 15px;" class="text-center">
      <h2>Welcome to the Castle Playground!</h2>
      <p class="lead">
        Users that log in here is monitored by the <b><a href="https://playground.castle.io" target="_BLANK">Castle demo app</a></b>.<br>Click around here with the demo app open in another window and watch the data appear.
      </p>
      <p>
        <%= link_to 'Sign up', sign_up_path, class: 'btn btn-lg btn-success' %>
      </p>
      <p style="margin-top: 40px;">
        <small>
          Source code of this app is <a href="https://github.com/castle/playground">available on Github</a>.
        </small>
      </p>
    </div>
  </div>
</div>

app/views/feedback/show.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8">
    <h2>Hi <%= @user.email %></h2>
  </div>
  <div class="col-sm-offset-2 col-sm-4">
    <% if @status == 'deny' %>
      <p>
        Oh no. Your account was probably hijacked. As a precaution we locked your account, which means you are going to be locked out from all of your devices.
        We've sent you an email with instructions on how to unlock your account again.
      </p>
    <% elsif @status == 'approve' %>
      <p>
        We approved your request.
        Thanks for providing us feedback!
      </p>
    <% else %>
      <p>Something went wrong</p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8 />
  <title>Castle Playground</title>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,700' rel='stylesheet' type='text/css'>
  <style>
    body {
      font-family: 'Source Sans Pro';
      font-size: 15px;
      line-height: 1.53;
    }
  </style>

  <!--
    Castle JavaScript tag
  -->
  <script type="text/javascript">
    (function(e,t,n,r){function i(e,n){e=t.createElement("script");e.async=1;e.src=r;n=t.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)}e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)};e.attachEvent?e.attachEvent("onload",i):e.addEventListener("load",i,false)})(window,document,"_castle","//d2t77mnxyo7adj.cloudfront.net/v1/c.js")
    _castle('setAppId', '<%= ENV["CASTLE_APP_ID"] %>');

    <% if current_user %>
    _castle('identify', '<%= current_user.id %>', {
      email: '<%= current_user.email %>',
      created_at: '<%= current_user.created_at %>'
    });
    _castle('secure', '<%= OpenSSL::HMAC.hexdigest("sha256", ENV["CASTLE_API_SECRET"], current_user.id.to_s) %>');
    <% end %>

    <% if ENV["CASTLE_API_ENDPOINT"] %>
    // For Castle internal use
    _castle('setTrackerUrl', '<%= ENV["CASTLE_API_ENDPOINT"] %>');
    <% end %>
  </script>

</head>
<body style="padding-top: 70px;">
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Castle Playground', root_path, class: 'navbar-brand' %>
      </div>
      <nav class="collapse navbar-collapse">
        <% if signed_in? %>
        <form class="navbar-form navbar-right" role="login">
          <%= link_to 'Log out', sign_out_path, method: :delete, class: 'btn btn-danger' %>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a>Logged in as: <%= current_user.email %></a>
          </li>
        </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
            </li>
          </ul>
          <form class="navbar-form navbar-right" role="login">
            <%= link_to 'Log in', sign_in_path, class: 'btn btn-success' %>
          </form>
        <% end %>
      </nav>
    </div>
  </div>
  <div class="container">
    <% if flash.any? %>
    <div id="flash" class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <% flash.each do |key, value| %>
          <div class="alert alert-warning flash <%= key %>">
            <%= value %>
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
    <%= yield %>
  </div>
  <%= javascript_include_tag :application %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <script type="text/javascript">
  $(".alert").alert()
  </script>

  <% if ENV['GA_TRACKING_CODE'].present? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', "<%= ENV['GA_TRACKING_CODE'] %>", 'auto');
    ga('send', 'pageview');
  </script>
  <% end %>
</body>
</html>

app/views/layouts/mail.html.erb
<html>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/mail_suspicious_activity.html.erb
<html>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="form-group">
  <%= form.text_field :email, type: 'email', placeholder: 'Email', class: "form-control", autofocus: true %>
</div>
<div class="form-group">
  <%= form.password_field :password, placeholder: 'Password', class: "form-control", autofocus: true %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div id="clearance" class="sign-up">
      <h2><%= t('.title') %></h2>
      <%= form_for @user do |form| %>
        <%= render :partial => '/users/form', :object => form %>
        <%= form.submit class: 'btn btn-primary pull-right' %>
        <%= link_to t('.sign_in'), sign_in_path, class: 'btn btn-link pull-right' %>
      <% end %>
    </div>
  </div>
</div>